package com.restaurante.persistence;

import com.restaurante.model.entity.CambioEstadoPedidoEntity;
import com.restaurante.model.entity.CuentaEntity;
import com.restaurante.model.entity.IngredienteEntity;
import com.restaurante.model.entity.ItemPedidoEntity;
import com.restaurante.model.entity.MesaEntity;
import com.restaurante.model.entity.PagoEntity;
import com.restaurante.model.entity.PedidoEntity;
import com.restaurante.model.entity.PlatoEntity;
import org.hibernate.boot.MetadataSources;
import org.hibernate.boot.registry.StandardServiceRegistryBuilder;
import org.junit.jupiter.api.Test;

import java.io.StringWriter;
import java.nio.file.Files;
import java.nio.file.Path;

import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

/** Genera el DDL con el Hibernate real del proyecto, sin conexión ni credenciales. */
class PostgreSqlSchemaTest {
    @Test
    void hibernateGeneraColumnaCalculadaRestriccionesYForeignKeysParaPostgres() throws Exception {
        StringWriter script = new StringWriter();
        var registry = new StandardServiceRegistryBuilder()
                .applySetting("hibernate.dialect", "org.hibernate.dialect.PostgreSQLDialect")
                .applySetting("hibernate.boot.allow_jdbc_metadata_access", false)
                .applySetting("jakarta.persistence.schema-generation.database.action", "none")
                .applySetting("jakarta.persistence.schema-generation.scripts.action", "create")
                .applySetting("jakarta.persistence.schema-generation.scripts.create-target", script)
                .build();
        try {
            var metadata = new MetadataSources(registry)
                    .addAnnotatedClass(MesaEntity.class)
                    .addAnnotatedClass(CuentaEntity.class)
                    .addAnnotatedClass(PedidoEntity.class)
                    .addAnnotatedClass(ItemPedidoEntity.class)
                    .addAnnotatedClass(PagoEntity.class)
                    .addAnnotatedClass(CambioEstadoPedidoEntity.class)
                    .addAnnotatedClass(PlatoEntity.class)
                    .addAnnotatedClass(IngredienteEntity.class)
                    .buildMetadata();
            try (var factory = metadata.buildSessionFactory()) {
                assertTrue(factory.isOpen());
            }
            String ddl = script.toString().replaceAll("\\s+", " ").toLowerCase();
            Files.writeString(Path.of("target/s09-1-postgresql-create.sql"), script.toString());
            assertTrue(ddl.contains("cuenta_abierta boolean generated always as "
                    + "(case when estado = 'abierta' then true else null end) stored"), ddl);
            assertTrue(ddl.contains("constraint uk_cuentas_mesa_abierta unique (mesa_id, cuenta_abierta)"), ddl);
            // OneToOne aporta una UNIQUE implícita; Hibernate la deduplica y puede
            // emitirla inline sin conservar el nombre declarado en @Table.
            String tablaPagos = ddl.substring(ddl.indexOf("create table pagos "),
                    ddl.indexOf(";", ddl.indexOf("create table pagos ")));
            assertTrue(tablaPagos.contains("cuenta_id bigint not null unique"), ddl);
            assertTrue(ddl.contains("generated by default as identity"), ddl);
            assertTrue(ddl.contains("foreign key (mesa_id) references mesas"), ddl);
            assertTrue(ddl.contains("foreign key (cuenta_id) references cuentas"), ddl);
            assertTrue(ddl.contains("foreign key (pedido_id) references pedidos"), ddl);
            assertFalse(ddl.matches(".*alter table if exists items_pedido[^;]*"
                    + "foreign key \\(plato_id\\) references platos.*"), ddl);
        } finally {
            StandardServiceRegistryBuilder.destroy(registry);
        }
    }
}
